[tools]
gcloud = "latest"

go = "latest"

java = "latest"

node = "latest"
"npm:@anthropic-ai/claude-code" = "latest"
"npm:@google/gemini-cli" = "latest"
"npm:@openai/codex" = "latest"
"npm:difit" = "latest"
"npm:mdts" = "latest"
"npm:node-gyp" = "latest"
"npm:oh-my-logo" = "latest"

python = "3.13"

ruby = "latest"
"gem:bitflyer-cli" = "latest"
"gem:circleci-cli" = "latest"
"gem:irasutoya-cli" = "latest"

rust = "stable"
"ubi:sst/opencode"= { version = "1.4.3", matching = "linux-x64.tar.gz", exe = "opencode" }
"npm:openclaw" = "latest"

[settings]
experimental = true
idiomatic_version_file_enable_tools = ["ruby"]
